### ISSUE TITLE
o-auth login and signup

### ISSUE THREAD

**Issue by devprashantt** [devprashantt/picstone-generative-ai#19]

**Comment by canavan-a** [comment]
Let's ship it from scratch and SQL use alchemy. I have an implementation with Postgres and redis to create cookie sessions. We could do the same with SQLAlchemy. What is your vision for content that authenticated users to be able to access?

**Comment by devprashantt** [comment]
> Let's ship it from scratch and SQL use alchemy. I have an implementation with Postgres and redis to create cookie sessions. We could do the same with SQLAlchemy. What is your vision for content that authenticated users to be able to access?

I am currently learning flask and sql databases, not much idea, if you are confident that you can do with sql-alchemy then goood to goo..
