### ISSUE TITLE
pytessaract not installed on system error on render

### ISSUE THREAD

**Issue by devprashantt** [devprashantt/picstone-generative-ai#45]

**Comment by canavan-a** [comment]
We just need to include in requirements.txt correct?

**Comment by devprashantt** [comment]
> We just need to include in requirements.txt correct?

no i think there is something else, as i have already included it in req. but its saying path not included in system on render, it need a driver for running img analysis.

**Comment by canavan-a** [comment]
We need to set up a separate container service:

https://community.render.com/t/deploying-a-python-tesseract-app-on-render/8365

I'm not sure where we can deploy containers for cheap.

Azure's free tier only lets you have 1 hour per day.

**Comment by devprashantt** [comment]
do you have idea about containers, i haven't worked before, try to setup as of now if u have idea.

**Comment by canavan-a** [comment]
I'll containerize the backend and push to Azure. 

I'll look into cheap container instances as well.
