### ISSUE TITLE
get user stories route needed

### ISSUE THREAD

**Issue by devprashantt** [devprashantt/picstone-generative-ai#53]

**Comment by canavan-a** [comment]
Let's get user story IDs and pull them individually. Just in case a user has a lot of stories.

**Comment by canavan-a** [comment]
Let's get user story IDs and pull them individually. Just in case a user has a lot of stories.

**Comment by devprashantt** [comment]
> Let's get user story IDs and pull them individually. Just in case a user has a lot of stories.

@nilmani9430 have pushed his code can u look into it nd do required changes or busy in other i can do that.

**Comment by canavan-a** [comment]
I can take a look right now

**Comment by canavan-a** [comment]
Okay, I made some changes to use the auth wrapper instead of an extra query. It looks good otherwise.

We are pulling stories, not just IDs, which is fine, but we may want to implement lazy loading for this in the future.
