### ISSUE TITLE
Possible compromise to data integrity, Transactions Not Atomic

### ISSUE THREAD

**Issue by Kyroyen** [devprashantt/picstone-generative-ai#60]
**Bug**

Possible bug on many instances, for example in main/server/controllers/user_controller.py.
If UserController.register_user() method would raise error an error after query execution, changes wouldn't be rolled back. 

>             query = 'INSERT INTO users (email, name, password_hash, salt, verification_id) VALUES (%s,%s,%s,%s,%s);'
>             verification_key = str(uuid.uuid4())
>             data = (email, name, hashed_password, salt, verification_key)
>             db.engine.execute(query, data)
>             parameterized_url = f"{os.environ.get('BACKEND_URL')}/verify?token={verification_key}"
>             email_content = render_template('verification_email.html', name=name, path=parameterized_url )
>             msg = Message("Picstone: Verify Email",
>                         sender="picstoneai@gmail.com",
>                         recipients=[email])

**Comment by canavan-a** [comment]
Ideally the data would be cached in some KV store like Redis. Upon confirmation with the email, the data would be stored in SQL. That is typically what I do I just have not set up a KV data store for this project yet. 

There may be another solution. psycopg2 lets you commit a query later on. I am unaware of a way to do this with SQLAlchemy. This could be another solution. Let me know your thoughts and thank you for bringing up this concern.

**Comment by canavan-a** [comment]
Another thought would be a try catch to remove the entry. (This doesn't seem like a very clean approach)

**Comment by canavan-a** [comment]
I made a PR for this fix.
